---
default_language_version:
  python: python3

repos:
  # precommit configuration meta-checks
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  # git
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
      - id: gitlint
  - repo: https://github.com/milin/gitown
    rev: v0.1.7
    hooks:
      - id: gitown
        args: [--codeowners_filename=.github/CODEOWNERS]
  - repo: https://github.com/mattlqx/pre-commit-sign
    rev: v1.1.3
    hooks:
      - id: sign-commit

  - repo: local
    hooks:
      - id: sort-codeowners
        name: alphabetize codeowners
        entry: scripts/alphabetize_codeowners.py
        language: python
        files: .github/CODEOWNERS

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: pretty-format-json
        args: [--autofix]

      # general
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude_types: [cmake]
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace

      # shell scripts
      - id: check-executables-have-shebangs

      # Python
      - id: check-ast
      - id: check-builtin-literals
      - id: debug-statements
      - id: fix-encoding-pragma

  # license header
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.12
    hooks:
      - id: insert-license
        name: "Insert license header"
        args: [--license-filepath=util/oranges_header.txt,
               --comment-style=#,
               --detect-license-in-X-top-lines=16]
        types_or: [cmake, python, shell]

  # text and typos
  - repo: https://github.com/sirosen/texthooks
    rev: 0.2.2
    hooks:
      - id: fix-ligatures
      - id: fix-smartquotes
      - id: forbid-bidi-controls
  - repo: https://github.com/crate-ci/typos
    rev: typos-v0.8.6
    hooks:
      - id: typos
        args: [--write-changes]

  # CMake
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        args: [--in-place]
    # - id: cmake-lint
    #   exclude: util/cmake/modules/integrations/scripts/run_clang_format.cmake

  # YAML
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.13.0
    hooks:
      - id: check-github-workflows

  # Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint-fix
        exclude: CHANGELOG.md

  # shell scripts
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
        args: [--tab]

  # Python
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/asottile/dead
    rev: v1.4.0
    hooks:
      - id: dead
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        args: [-i]
  - repo: https://github.com/PyCQA/pylint
    rev: v2.12.2
    hooks:
      - id: pylint

  # check editorconfig rules
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.4.0
    hooks:
      - id: editorconfig-checker
        always_run: true

ci:
  skip: [gitown]
  autofix_commit_msg: 'style: pre-commit autofixes [skip ci]'
  autoupdate_commit_msg: 'chore: pre-commit autoupdate [skip ci]'
