---
# editorconfig-checker-disable
# yamllint disable rule:line-length

default_language_version:
    python: python3

repos:
  # precommit configuration meta-checks
    - repo: meta
      hooks:
          - id: check-hooks-apply
            always_run: true
          - id: check-useless-excludes
            always_run: true

  # git
    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.17.0
      hooks:
          - id: gitlint
            always_run: true
    - repo: https://github.com/mattlqx/pre-commit-sign
      rev: v1.1.3
      hooks:
          - id: sign-commit

    - repo: local
      hooks:
          # run cmake & update dependency graph & readme
          - id: run-cmake
            name: Run CMake
            entry: cmake --preset default
            language: system
            always_run: true
            pass_filenames: false

          - id: update-readme
            name: Update readme
            entry: cmake --build --preset readme
            language: system
            always_run: true
            pass_filenames: false

    # - repo: https://github.com/andreoliwa/nitpick
    #   rev: v0.32.0
    #   hooks:
    #       - id: nitpick

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
          - id: check-json
          - id: check-yaml
          - id: check-toml
          - id: pretty-format-json
            args: [--autofix]

      # general
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: end-of-file-fixer
            exclude_types: [cmake]
          - id: fix-byte-order-marker
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: trailing-whitespace

      # Python
          - id: check-ast
          - id: check-builtin-literals
          - id: debug-statements
          - id: fix-encoding-pragma

  # license header
    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.1.13 # last known stable version is v1.1.13
      hooks:
          - id: insert-license
            name: Insert license header
            args: [--license-filepath=util/oranges_header.txt, --comment-style=#, --detect-license-in-X-top-lines=16]
            types_or: [cmake, python, shell]

  # text and typos
    - repo: https://github.com/sirosen/texthooks
      rev: 0.3.1
      hooks:
          - id: fix-ligatures
          - id: fix-smartquotes
          - id: forbid-bidi-controls
    - repo: https://github.com/crate-ci/typos
      rev: typos-dict-v0.8.2 # last known stable version is typos-dict-v0.8.2
      hooks:
          - id: typos
            args: [--write-changes]
            exclude: CHANGELOG.md|OrangesOptimizationFlags.cmake

  # CMake
    - repo: https://github.com/cheshirekow/cmake-format-precommit
      rev: v0.6.13
      hooks:
          - id: cmake-format
            args: [--in-place]
          #- id: cmake-lint

  # YAML
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.1
      hooks:
          - id: yamlfmt
            args: [--width, '200', --preserve-quotes]
    - repo: https://github.com/adrienverge/yamllint
      rev: v1.26.3
      hooks:
          - id: yamllint
    - repo: https://github.com/sirosen/check-jsonschema
      rev: 0.14.3 # last known stable version is 0.14.3
      hooks:
          - id: check-github-workflows
          - id: check-jsonschema
            name: Validate CMake presets
            files: CMakePresets.json
            types: [json]
            args: [--schemafile, "https://cmake.org/cmake/help/latest/_downloads/3e2d73bff478d88a7de0de736ba5e361/schema.json"]

  # Markdown
    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.31.1
      hooks:
          - id: markdownlint-fix
            exclude: CHANGELOG.md

  # TOML
    - repo: https://github.com/pappasam/toml-sort
      rev: v0.20.0
      hooks:
          - id: toml-sort
            args: [--in-place, --all]

  # shell scripts
    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.8.0.4
      hooks:
          - id: shellcheck
    - repo: https://github.com/lovesegfault/beautysh
      rev: v6.2.1
      hooks:
          - id: beautysh
            args: [--tab]

  # Python
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.32.1
      hooks:
          - id: pyupgrade
    - repo: https://github.com/myint/autoflake
      rev: v1.4
      hooks:
          - id: autoflake
    - repo: https://github.com/pre-commit/mirrors-yapf
      rev: v0.32.0
      hooks:
          - id: yapf
            args: [-i]
    - repo: https://github.com/PyCQA/pylint
      rev: v2.13.8 # last known stable version is v2.13.8
      hooks:
          - id: pylint
            args: [--disable=bad-indentation, --disable=line-too-long, --disable=duplicate-code, --check-quote-consistency=yes, --max-args=5, --max-branches=15, --max-statements=55, --good-names=f]
    - repo: https://github.com/PyCQA/docformatter
      rev: v1.4
      hooks:
          - id: docformatter
            args: [--in-place, --recursive, --wrap-summaries, '150', --wrap-descriptions, '150', --pre-summary-newline, --make-summary-multi-line]

  # check editorconfig rules
    - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
      rev: 2.4.0
      hooks:
          - id: editorconfig-checker
            exclude: oranges_header.txt|LICENSE|index.rst|Doxyfile|standard_header.h|platform_header.h

ci:
    skip: [check-jsonschema, pylint, run-cmake, update-readme]
    autofix_commit_msg: 'style: pre-commit autofixes [skip ci]'
    autoupdate_commit_msg: 'chore: pre-commit autoupdate [skip ci]'
