---
version: 2

python:
    install:
        - requirements: docs/requirements.txt
    system_packages: true

build:
    os: "ubuntu-22.04"
    tools:
        python: "3.9"
    commands:
        - cmake -B Builds -S . -D ORANGES_BUILD_DOCS=ON
        - cmake --build Builds
        - mv doc/html/* _readthedocs/html/

sphinx:
    builder: html
    configuration: Builds/docs/conf.py

formats: all
