/*
This file was generated by CMake, any changes will be overwritten!

Generated by the @CMAKE_CURRENT_FUNCTION@ function, Oranges version @Oranges_VERSION@
*/

#pragma once

#define @ORANGES_ARG_BASE_NAME@_DEBUG $<IN_LIST:$<CONFIG>,@ORANGES_DEBUG_CONFIGS_LIST@>

#define @ORANGES_ARG_BASE_NAME@_RELEASE $<NOT:$<IN_LIST:$<CONFIG>,@ORANGES_DEBUG_CONFIGS_LIST@>>

#define @ORANGES_ARG_BASE_NAME@_BUILD_TYPE "$<CONFIG>"
