/*
This file was generated by CMake, any changes will be overwritten!

Generated by the @CMAKE_CURRENT_FUNCTION@ function, Oranges version @Oranges_VERSION@
*/

#pragma once

#include ORANGES_BUILD_TYPE_HEADER_NAME  // IWYU pragma: export
