/*
This file was generated by CMake, any changes will be overwritten!

Generated by the @CMAKE_CURRENT_FUNCTION@() function, Oranges version @Oranges_VERSION@.
*/

#pragma once

/*-----------------------------------------------------------------------------------------------------------------------*/

// OS type macros

#define @ORANGES_ARG_BASE_NAME@_UNIX @_PLAT_UNIX@
#define @ORANGES_ARG_BASE_NAME@_POSIX @_PLAT_POSIX@

#define @ORANGES_ARG_BASE_NAME@_WINDOWS @_PLAT_WIN@
#define @ORANGES_ARG_BASE_NAME@_MINGW @_PLAT_MINGW@

#define @ORANGES_ARG_BASE_NAME@_LINUX @_PLAT_LINUX@

#define @ORANGES_ARG_BASE_NAME@_APPLE @_PLAT_APPLE@
#define @ORANGES_ARG_BASE_NAME@_OSX @_PLAT_MACOSX@
#define @ORANGES_ARG_BASE_NAME@_IOS @_PLAT_IOS@

#define @ORANGES_ARG_BASE_NAME@_ANDROID @_PLAT_ANDROID@

#define @ORANGES_ARG_BASE_NAME@_MOBILE @_PLAT_MOBILE@
#define @ORANGES_ARG_BASE_NAME@_EMBEDDED @_PLAT_EMBEDDED@

#define @ORANGES_ARG_BASE_NAME@_OS_TYPE "@PLAT_OS_TYPE@"

/*-----------------------------------------------------------------------------------------------------------------------*/

// compiler type macros

#define @ORANGES_ARG_BASE_NAME@_CLANG @_PLAT_CLANG@

#define @ORANGES_ARG_BASE_NAME@_GCC @_PLAT_GCC@

#define @ORANGES_ARG_BASE_NAME@_MSVC @_PLAT_MSVC@

#define @ORANGES_ARG_BASE_NAME@_INTEL_COMPILER @_PLAT_INTEL_COMPILER@

#define @ORANGES_ARG_BASE_NAME@_CRAY_COMPILER @_PLAT_CRAY_COMPILER@

#define @ORANGES_ARG_BASE_NAME@_ARM_COMPILER @_PLAT_ARM_COMPILER@

#define @ORANGES_ARG_BASE_NAME@_COMPILER_TYPE "@PLAT_COMPILER_TYPE@"

// compiler version macros

#define @ORANGES_ARG_BASE_NAME@_COMPILER_VERSION_MAJOR @PLAT_COMPILER_VERSION_MAJOR@

#define @ORANGES_ARG_BASE_NAME@_COMPILER_VERSION_MINOR @PLAT_COMPILER_VERSION_MINOR@

#define @ORANGES_ARG_BASE_NAME@_COMPILER_VERSION_PATCH @PLAT_COMPILER_VERSION_PATCH@

#define @ORANGES_ARG_BASE_NAME@_COMPILER_VERSION "@PLAT_COMPILER_VERSION@"

/*-----------------------------------------------------------------------------------------------------------------------*/

// processor type macros

#define @ORANGES_ARG_BASE_NAME@_ARM @_PLAT_ARM@
#define @ORANGES_ARG_BASE_NAME@_INTEL @_PLAT_INTEL@
#define @ORANGES_ARG_BASE_NAME@_CPU_TYPE "@PLAT_CPU_TYPE@"

#define @ORANGES_ARG_BASE_NAME@_64BIT @_PLAT_64BIT@
#define @ORANGES_ARG_BASE_NAME@_32BIT @_PLAT_32BIT@

#define @ORANGES_ARG_BASE_NAME@_BIG_ENDIAN @_PLAT_BIG_ENDIAN@
#define @ORANGES_ARG_BASE_NAME@_LITTLE_ENDIAN @_PLAT_LITTLE_ENDIAN@

/*-----------------------------------------------------------------------------------------------------------------------*/

// SIMD instruction capabilities

#define @ORANGES_ARG_BASE_NAME@_ARM_NEON @_PLAT_ARM_NEON@

#define @ORANGES_ARG_BASE_NAME@_AVX @_PLAT_AVX@
#define @ORANGES_ARG_BASE_NAME@_AVX512 @_PLAT_AVX512@

#define @ORANGES_ARG_BASE_NAME@_SSE @_PLAT_SSE@

/*-----------------------------------------------------------------------------------------------------------------------*/
