/*
This file was generated by CMake, any changes will be overwritten!

Generated by the @CMAKE_CURRENT_FUNCTION@ function, Oranges version @Oranges_VERSION@
*/

#pragma once

/*-----------------------------------------------------------------------------------------------------------------------*/

// OS type macros

#define @ORANGES_ARG_BASE_NAME@_UNIX @PLAT_UNIX@
#define @ORANGES_ARG_BASE_NAME@_POSIX @PLAT_POSIX@

#define @ORANGES_ARG_BASE_NAME@_WINDOWS @PLAT_WIN@
#define @ORANGES_ARG_BASE_NAME@_MINGW @PLAT_MINGW@

#define @ORANGES_ARG_BASE_NAME@_LINUX @PLAT_LINUX@

#define @ORANGES_ARG_BASE_NAME@_APPLE @PLAT_APPLE@
#define @ORANGES_ARG_BASE_NAME@_OSX @PLAT_MACOSX@
#define @ORANGES_ARG_BASE_NAME@_IOS @PLAT_IOS@

#define @ORANGES_ARG_BASE_NAME@_ANDROID @PLAT_ANDROID@

#define @ORANGES_ARG_BASE_NAME@_MOBILE @PLAT_MOBILE@
#define @ORANGES_ARG_BASE_NAME@_EMBEDDED @PLAT_EMBEDDED@

#define @ORANGES_ARG_BASE_NAME@_OS_TYPE "@PLAT_OS_TYPE@"

/*-----------------------------------------------------------------------------------------------------------------------*/

// compiler type macros

#define @ORANGES_ARG_BASE_NAME@_CLANG @PLAT_CLANG_@ORANGES_ARG_LANGUAGE@@

#define @ORANGES_ARG_BASE_NAME@_GCC @PLAT_GCC_@ORANGES_ARG_LANGUAGE@@

#define @ORANGES_ARG_BASE_NAME@_MSVC @PLAT_MSVC_@ORANGES_ARG_LANGUAGE@@

#define @ORANGES_ARG_BASE_NAME@_INTEL_COMPILER @PLAT_INTEL_COMPILER_@ORANGES_ARG_LANGUAGE@@

#define @ORANGES_ARG_BASE_NAME@_CRAY_COMPILER @PLAT_CRAY_COMPILER_@ORANGES_ARG_LANGUAGE@@

#define @ORANGES_ARG_BASE_NAME@_ARM_COMPILER @PLAT_ARM_COMPILER_@ORANGES_ARG_LANGUAGE@@

#define @ORANGES_ARG_BASE_NAME@_COMPILER_TYPE "@PLAT_COMPILER_TYPE_@ORANGES_ARG_LANGUAGE@@"

#define @ORANGES_ARG_BASE_NAME@_COMPILER_VERSION_MAJOR @PLAT_COMPILER_VERSION_MAJOR_@ORANGES_ARG_LANGUAGE@@

#define @ORANGES_ARG_BASE_NAME@_COMPILER_VERSION_MINOR @PLAT_COMPILER_VERSION_MINOR_@ORANGES_ARG_LANGUAGE@@

#define @ORANGES_ARG_BASE_NAME@_COMPILER_VERSION_PATCH @PLAT_COMPILER_VERSION_PATCH_@ORANGES_ARG_LANGUAGE@@

#define @ORANGES_ARG_BASE_NAME@_COMPILER_VERSION "@PLAT_COMPILER_VERSION_@ORANGES_ARG_LANGUAGE@@"

/*-----------------------------------------------------------------------------------------------------------------------*/

// processor type macros

#define @ORANGES_ARG_BASE_NAME@_ARM @PLAT_ARM@
#define @ORANGES_ARG_BASE_NAME@_INTEL @PLAT_INTEL@
#define @ORANGES_ARG_BASE_NAME@_CPU_TYPE "@PLAT_CPU_TYPE@"

#define @ORANGES_ARG_BASE_NAME@_64BIT @PLAT_64BIT@
#define @ORANGES_ARG_BASE_NAME@_32BIT @PLAT_32BIT@

#define @ORANGES_ARG_BASE_NAME@_BIG_ENDIAN @ORANGES_BIG_ENDIAN_@ORANGES_ARG_LANGUAGE@@
#define @ORANGES_ARG_BASE_NAME@_LITTLE_ENDIAN @ORANGES_LITTLE_ENDIAN_@ORANGES_ARG_LANGUAGE@@

/*-----------------------------------------------------------------------------------------------------------------------*/

// SIMD instruction capabilities

#define @ORANGES_ARG_BASE_NAME@_ARM_NEON @PLAT_ARM_NEON@

#define @ORANGES_ARG_BASE_NAME@_AVX @PLAT_AVX@
#define @ORANGES_ARG_BASE_NAME@_AVX512 @PLAT_AVX512@

#define @ORANGES_ARG_BASE_NAME@_SSE @PLAT_SSE@

/*-----------------------------------------------------------------------------------------------------------------------*/
