/*
======================================================================================
   ____  _____            _   _  _____ ______  _____
  / __ \|  __ \     /\   | \ | |/ ____|  ____|/ ____|
 | |  | | |__) |   /  \  |  \| | |  __| |__  | (___
 | |  | |  _  /   / /\ \ | . ` | | |_ |  __|  \___ \
 | |__| | | \ \  / ____ \| |\  | |__| | |____ ____) |
  \____/|_|  \_\/_/    \_\_| \_|\_____|______|_____/

 This file is part of the Oranges open source CMake library and is licensed under the terms of the GNU Public License.

======================================================================================

This file was generated by CMake, any changes will be overwritten!

Generated by the @CMAKE_CURRENT_FUNCTION@ function, Oranges version @Oranges_VERSION@.
*/

#pragma once

#include <@ORANGES_ARG_EXPORT_HEADER@>  // export header
#include <@ORANGES_ARG_PLATFORM_HEADER@>  // platform header
