/*
This file was generated by CMake, any changes will be overwritten!

Generated by the @CMAKE_CURRENT_FUNCTION@ function, Oranges version @Oranges_VERSION@
*/

#pragma once

#include <@ORANGES_ARG_EXPORT_HEADER@>  // export header
#include <@ORANGES_ARG_PLATFORM_HEADER@>  // platform header
