---
name: Create release

# yamllint disable rule:line-length

on:
    workflow_dispatch:
    push:
        branches:
            - main
    schedule:
        - cron: 0 0 * * 1

defaults:
    run:
        shell: bash

jobs:

    Build:

        name: Build
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:

            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  submodules: recursive
                  fetch-depth: 1

            - uses: actions/setup-python@v3
              with:
                  python-version: '3.9'

            - name: Configure CMake
              run: cmake --preset maintainer

            - name: Run build
              run: cmake --build --preset maintainer --config Debug

            - name: Create install tree
              run: cmake --install Builds --config Debug --prefix '${{ github.workspace }}/deploy'

            - name: Upload artefacts
              uses: actions/upload-artifact@v3
              with:
                  name: Oranges
                  path: '${{ github.workspace }}/deploy'
                  if-no-files-found: error


    Release:

        name: Create release
        runs-on: ubuntu-latest
        needs: Build

        steps:

            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  submodules: recursive
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3.3.0
              with:
                  node-version: lts/*

            - name: Install dependencies
              run: npm install

            - name: Install dependencies
              run: pip install --upgrade bumpversion

            - name: Download artefacts
              uses: actions/download-artifact@v3
              with:
                  path: '${{ github.workspace }}/deploy'

            - name: Zip artefact
              run: cmake -E tar cvz Oranges.zip '${{ github.workspace }}/deploy/Oranges'

            - name: Run semantic release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release
